### ISSUE TITLE
container is not VM

### ISSUE THREAD

**Issue by martinvelos** [MicrosoftDocs/azure-docs.cs-cz#135]
"steps in publishing a VM offer" seem like a copy&paste artifact, highly misleading.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 68967fb7-9a16-66a7-8ea4-d40786e6a5ef
* Version Independent ID: c532e02c-6194-7e67-72bd-9a74eee0ce58
* Content: [Nabídka Azure image kontejnerů](https://docs.microsoft.com/cs-cz/azure/marketplace/cloud-partner-portal/containers/cpp-containers-offer#feedback)
* Content Source: [articles/marketplace/cloud-partner-portal/containers/cpp-containers-offer.md](https://github.com/MicrosoftDocs/azure-docs.cs-cz/blob/live/articles/marketplace/cloud-partner-portal/containers/cpp-containers-offer.md)
* Service: **marketplace**
* GitHub Login: @dan-wesley
* Microsoft Alias: **pbutlerm**

**Comment by CeciAc** [comment]
Hello, @martinvelos 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here -https://github.com/MicrosoftDocs/azure-docs/issues/28656

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
