### ISSUE TITLE
change calculation to not inflate the size if rounded already

### ISSUE THREAD

**Issue by beerwatch** [MicrosoftDocs/azure-docs.cs-cz#151]
Your expression
`rounded_size=$((($size/$MB + 1)*$MB))`
always inflates the size by 1MB, even for files which are already meeting the requirement.
A more apropriate calculation is
`rounded_size=$(((($size+$MB-1)/$MB)*$MB))`
I propose a change.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 500c614f-c910-4999-904e-013b6f1cd152
* Version Independent ID: 6a50cc70-92c9-b0eb-850b-4ed0be9d2159
* Content: [Vytvoření a nahrání VHD s Linuxem v Azure](https://docs.microsoft.com/cs-cz/azure/virtual-machines/linux/create-upload-generic#feedback)
* Content Source: [articles/virtual-machines/linux/create-upload-generic.md](https://github.com/MicrosoftDocs/azure-docs.cs-cz/blob/live/articles/virtual-machines/linux/create-upload-generic.md)
* Service: **virtual-machines-linux**
* GitHub Login: @szarkos
* Microsoft Alias: **szark**

**Comment by CeciAc** [comment]
Hello, @beerwatch 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/29804

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
