### ISSUE TITLE
NSG for GatewaySubnet

### ISSUE THREAD

**Issue by hadr10** [MicrosoftDocs/azure-docs.cs-cz#483]
Hello,

how i can associate nsg for gatewaySubnet? I want to use for nsg flow logs -&gt; traffic analytics.
Failed to save subnet 'GatewaySubnet'. Error: 'The operation failed because the network security group can not be associated to the GatewaySubnet. Please remove the network security group associated to the GatewaySubnet. No changes have occurred on the gateway at this time. See here for additional details: https://aka.ms/GatewaySubnet.'

Thank you

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 59a0b9f5-9071-5e89-5f52-ca8fb2dbc90b
* Version Independent ID: 61a1736f-56c1-7950-72b3-907f32689ca4
* Content: [Analýza provozu Azure](https://docs.microsoft.com/cs-cz/azure/network-watcher/traffic-analytics)
* Content Source: [articles/network-watcher/traffic-analytics.md](https://github.com/MicrosoftDocs/azure-docs.cs-cz/blob/master/articles/network-watcher/traffic-analytics.md)
* Service: **network-watcher**
* GitHub Login: @damendo
* Microsoft Alias: **damendo**

**Comment by srvbpigh** [comment]
Hello, @hadr10
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @hadr10, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/48607. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
