### ISSUE TITLE
Link in section 3 is bad and returns 404

### ISSUE THREAD

**Issue by pfrcka** [MicrosoftDocs/azure-docs.cs-cz#96]
Instead of https://azuremarketplace.microsoft.com/sell/signup there should be https://azuremarketplace.microsoft.com/en-us/sell/signup

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: e16147fb-8da4-6c41-be0f-b2856043c7c9
* Version Independent ID: dab8f3c3-c3ff-883b-406d-405701a53224
* Content: [Stát vydavatelem na prodejní místa na webu marketplace](https://docs.microsoft.com/cs-cz/azure/marketplace/become-publisher#3-submit-the-marketplace-registration-form)
* Content Source: [articles/marketplace/become-publisher.md](https://github.com/MicrosoftDocs/azure-docs.cs-cz/blob/live/articles/marketplace/become-publisher.md)
* Service: **marketplace**
* GitHub Login: @ellacroi
* Microsoft Alias: **ellacroi**

**Comment by CeciAc** [comment]
Hi @pfrcka 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. 

The link you mention would it be this one, right?
![imagen](https://user-images.githubusercontent.com/26746247/51040521-7f81c700-1596-11e9-806c-db5b806fb11b.png)

I  cannot repro this error, the link works fine on my side.
Please let me know if the issue persists and kindly provide additional information so we can help you

Kind regards,
Microsoft DOCS International Team

**Comment by ellacroi** [comment]
@dsindona it looks like the feedback here is to add back in the geo domain information (en-us), which is standard practice to remove for localization purposes. Is there a third option we should change it to?

**Comment by dsindona** [comment]
@pfrcka Can you see what URL is trying to render from that link from your locale? https://azuremarketplace.microsoft.com/cs-cz/sell/signup
or something else?  
@SunnyDeng @ishasahni1 for awareness

**Comment by CeciAc** [comment]
Hi @SunnyDeng 
any updates on this?
@dsindona @ellacroi
cc @ishasahni1

**Comment by SunnyDeng** [comment]
@honghuig is following up with Azure Market place dev. 
@honghuig do we have any updates?

**Comment by ishasahni1** [comment]
@honghuig any update on this?

cc @CeciAc

**Comment by CeciAc** [comment]
@honghuig any update on this?

**Comment by honghuig** [comment]
@CeciAc I contacted core team again and sent the trace log. They are investigating.

**Comment by CeciAc** [comment]
Closing this issue since the page was reverted to en-us
